services:
    account-service:
        image: accounts-service
        build: ./account-service/
        container_name: accounts-service
        restart: always
        ports:
            - "8081:8081"

    course-service:
        image: courses-service
        build: ./course-service/
        container_name: courses-service
        restart: always
        ports:
            - "8080:8080"
            - "9990:9990"

    client-service:
        image: client-service
        build: ./client/
        container_name: client-service
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_COURSE=localhost
            - NEXT_PUBLIC_ACCOUNT=localhost
