apiVersion: v1
kind: Service
metadata:
    name: accounts-service
    namespace: online-learning-platform-namespace
spec:
    selector:
        app: accounts-microservice
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
    type: ClusterIP
